# Generated by Django 6.0 on 2025-12-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('monitor', 'Monitor'), ('keyboard', 'Klawiatura'), ('mouse', 'Mysz'), ('headphones', 'Słuchawki'), ('projector', 'Projektor'), ('camera', 'Kamera'), ('other', 'Inne')], max_length=50, verbose_name='Kategoria')),
                ('description', models.TextField(verbose_name='Opis')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sprzęt',
                'verbose_name_plural': 'Sprzęt',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='Data wynajmu')),
                ('return_date', models.DateField(verbose_name='Data zwrotu')),
                ('status', models.CharField(choices=[('active', 'Aktywne'), ('completed', 'Ukończone'), ('cancelled', 'Anulowane')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rental.equipment', verbose_name='Sprzęt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wypożyczenie',
                'verbose_name_plural': 'Wypożyczenia',
            },
        ),
    ]
